import { ScriptConfig } from "./types.js";
import { parseJsonSafely } from "./utils.js";

const FEATURE_FLAG_REQUEST_TIMEOUT_MS = 2000;
const INLINE_CONFIG_ATTRIBUTES = [
  "data-session-replay",
  "data-web-vitals",
  "data-track-errors",
  "data-track-outbound",
  "data-track-url-params",
  "data-track-initial-pageview",
  "data-track-spa-navigation",
  "data-track-button-clicks",
  "data-track-copy",
  "data-track-form-interactions",
] as const;

type FeatureFlagFetchResult = {
  enabled: boolean;
  flags: ScriptConfig["featureFlags"];
};

function getBooleanAttribute(scriptTag: HTMLScriptElement, name: string, defaultValue: boolean): boolean {
  const value = scriptTag.getAttribute(name);
  return value === null ? defaultValue : value !== "false";
}

function hasInlineTrackingConfig(scriptTag: HTMLScriptElement): boolean {
  return (
    scriptTag.getAttribute("data-config-mode") === "inline" ||
    // Snippets generated by this fork before data-config-mode was introduced
    // already carried every setting and should remain request-free.
    INLINE_CONFIG_ATTRIBUTES.every(attribute => scriptTag.hasAttribute(attribute))
  );
}

function createVisitorId(): string {
  try {
    if (crypto?.randomUUID) {
      return crypto.randomUUID();
    }
  } catch (e) {
    // crypto may be unavailable in older browsers
  }

  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
}

function getOrCreateVisitorId(namespace: string): string {
  const key = `${namespace}-visitor-id`;

  try {
    const stored = localStorage.getItem(key);
    if (stored) return stored;

    const visitorId = createVisitorId();
    localStorage.setItem(key, visitorId);
    return visitorId;
  } catch (e) {
    return createVisitorId();
  }
}

function getIdentifiedUserId(namespace: string): string | undefined {
  try {
    return localStorage.getItem(`${namespace}-user-id`) || undefined;
  } catch (e) {
    return undefined;
  }
}

function getEvaluationPathname(url: URL): string {
  if (url.hash && url.hash.startsWith("#/")) {
    return url.hash.substring(1);
  }

  return url.pathname;
}

async function fetchFeatureFlags(
  analyticsHost: string,
  siteId: string,
  namespace: string,
  visitorId: string
): Promise<FeatureFlagFetchResult> {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), FEATURE_FLAG_REQUEST_TIMEOUT_MS);

  try {
    const url = new URL(window.location.href);
    const response = await fetch(`${analyticsHost}/site/${siteId}/feature-flags/evaluate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "omit",
      signal: controller.signal,
      body: JSON.stringify({
        anonymousId: visitorId,
        identifiedUserId: getIdentifiedUserId(namespace),
        hostname: url.hostname,
        pathname: getEvaluationPathname(url),
        querystring: url.search,
        query: Object.fromEntries(url.searchParams.entries()),
        referrer: document.referrer,
        language: navigator.language,
        screenWidth: screen.width,
        screenHeight: screen.height,
      }),
    });

    if (!response.ok) {
      return { enabled: true, flags: {} };
    }

    const data = await response.json();
    return {
      enabled: data?.featureFlagsEnabled !== false,
      flags: data?.flags && typeof data.flags === "object" ? data.flags : {},
    };
  } catch (e) {
    return { enabled: true, flags: {} };
  } finally {
    window.clearTimeout(timeout);
  }
}

/**
 * Parse minimal script configuration from the script tag attributes
 * Most configuration will be fetched from the API
 */
export async function parseScriptConfig(scriptTag: HTMLScriptElement): Promise<ScriptConfig | null> {
  const src = scriptTag.getAttribute("src");
  if (!src) {
    console.error("Script src attribute is missing");
    return null;
  }

  const analyticsHost = src.split("/script.js")[0];
  if (!analyticsHost) {
    console.error("Please provide a valid analytics host");
    return null;
  }

  const siteId = scriptTag.getAttribute("data-site-id") || scriptTag.getAttribute("site-id");
  if (!siteId) {
    console.error("Please provide a valid site ID using the data-site-id attribute");
    return null;
  }

  const namespace = scriptTag.getAttribute("data-namespace") || "rybbit";
  const visitorId = getOrCreateVisitorId(namespace);

  // These can be overridden via data attributes for testing/debugging
  const skipPatterns = parseJsonSafely<string[]>(scriptTag.getAttribute("data-skip-patterns"), []);
  const maskPatterns = parseJsonSafely<string[]>(scriptTag.getAttribute("data-mask-patterns"), []);
  const sessionReplayMaskTextSelectors = parseJsonSafely<string[]>(
    scriptTag.getAttribute("data-replay-mask-text-selectors"),
    []
  );

  const debounceDuration = scriptTag.getAttribute("data-debounce")
    ? Math.max(0, parseInt(scriptTag.getAttribute("data-debounce")!))
    : 500;

  const sessionReplayBatchSize = scriptTag.getAttribute("data-replay-batch-size")
    ? Math.max(1, parseInt(scriptTag.getAttribute("data-replay-batch-size")!))
    : 250;

  const sessionReplayBatchInterval = scriptTag.getAttribute("data-replay-batch-interval")
    ? Math.max(1000, parseInt(scriptTag.getAttribute("data-replay-batch-interval")!))
    : 5000;

  // Parse rrweb session replay options
  const sessionReplayBlockClass = scriptTag.getAttribute("data-replay-block-class") || undefined;
  const sessionReplayBlockSelector = scriptTag.getAttribute("data-replay-block-selector") || undefined;
  const sessionReplayIgnoreClass = scriptTag.getAttribute("data-replay-ignore-class") || undefined;
  const sessionReplayIgnoreSelector = scriptTag.getAttribute("data-replay-ignore-selector") || undefined;
  const sessionReplayMaskTextClass = scriptTag.getAttribute("data-replay-mask-text-class") || undefined;

  const maskAllInputsAttr = scriptTag.getAttribute("data-replay-mask-all-inputs");
  const sessionReplayMaskAllInputs = maskAllInputsAttr !== null ? maskAllInputsAttr !== "false" : undefined;

  const maskInputOptionsAttr = scriptTag.getAttribute("data-replay-mask-input-options");
  const sessionReplayMaskInputOptions = maskInputOptionsAttr
    ? parseJsonSafely<Record<string, boolean>>(maskInputOptionsAttr, { password: true, email: true })
    : undefined;

  const collectFontsAttr = scriptTag.getAttribute("data-replay-collect-fonts");
  const sessionReplayCollectFonts = collectFontsAttr !== null ? collectFontsAttr !== "false" : undefined;

  const samplingAttr = scriptTag.getAttribute("data-replay-sampling");
  const sessionReplaySampling = samplingAttr ? parseJsonSafely<Record<string, any>>(samplingAttr, {}) : undefined;

  const slimDOMAttr = scriptTag.getAttribute("data-replay-slim-dom-options");
  const sessionReplaySlimDOMOptions = slimDOMAttr
    ? parseJsonSafely<Record<string, boolean> | boolean>(slimDOMAttr, {})
    : undefined;

  const sampleRateAttr = scriptTag.getAttribute("data-replay-sample-rate");
  const sessionReplaySampleRate = sampleRateAttr ? Math.min(100, Math.max(0, parseInt(sampleRateAttr, 10))) : undefined;

  const tag = scriptTag.getAttribute("data-tag") || "";

  const inlineTrackingConfig = hasInlineTrackingConfig(scriptTag);

  // Data attributes are authoritative for request-free inline snippets. For a
  // regular upstream-style snippet these defaults are replaced by the API.
  const defaultConfig: ScriptConfig = {
    namespace,
    analyticsHost,
    siteId,
    visitorId,
    debounceDuration,
    sessionReplayBatchSize,
    sessionReplayBatchInterval,
    sessionReplayMaskTextSelectors,
    skipPatterns,
    maskPatterns,
    autoTrackPageview: getBooleanAttribute(scriptTag, "data-track-initial-pageview", true),
    autoTrackSpa: getBooleanAttribute(scriptTag, "data-track-spa-navigation", true),
    trackQuerystring: getBooleanAttribute(scriptTag, "data-track-url-params", true),
    trackOutbound: getBooleanAttribute(scriptTag, "data-track-outbound", true),
    enableWebVitals: getBooleanAttribute(scriptTag, "data-web-vitals", false),
    trackErrors: getBooleanAttribute(scriptTag, "data-track-errors", false),
    enableSessionReplay: getBooleanAttribute(scriptTag, "data-session-replay", false),
    trackButtonClicks: getBooleanAttribute(scriptTag, "data-track-button-clicks", false),
    trackCopy: getBooleanAttribute(scriptTag, "data-track-copy", false),
    trackFormInteractions: getBooleanAttribute(scriptTag, "data-track-form-interactions", false),
    tag,
    featureFlagsEnabled: getBooleanAttribute(scriptTag, "data-feature-flags-enabled", false),
    featureFlags: {},
    // rrweb session replay options (undefined means use rrweb defaults)
    sessionReplayBlockClass,
    sessionReplayBlockSelector,
    sessionReplayIgnoreClass,
    sessionReplayIgnoreSelector,
    sessionReplayMaskTextClass,
    sessionReplayMaskAllInputs,
    sessionReplayMaskInputOptions,
    sessionReplayCollectFonts,
    sessionReplaySampling,
    sessionReplaySlimDOMOptions,
    sessionReplaySampleRate,
  };

  let resolvedConfig = defaultConfig;

  if (!inlineTrackingConfig) {
    try {
      // Fetch configuration from API for ordinary minimal snippets.
      const configUrl = `${analyticsHost}/site/tracking-config/${siteId}`;
      const response = await fetch(configUrl, {
        method: "GET",
        credentials: "omit",
      });

      if (response.ok) {
        const apiConfig = await response.json();

        resolvedConfig = {
          ...defaultConfig,
          autoTrackPageview: apiConfig.trackInitialPageView ?? defaultConfig.autoTrackPageview,
          autoTrackSpa: apiConfig.trackSpaNavigation ?? defaultConfig.autoTrackSpa,
          trackQuerystring: apiConfig.trackUrlParams ?? defaultConfig.trackQuerystring,
          trackOutbound: apiConfig.trackOutbound ?? defaultConfig.trackOutbound,
          enableWebVitals: apiConfig.webVitals ?? defaultConfig.enableWebVitals,
          trackErrors: apiConfig.trackErrors ?? defaultConfig.trackErrors,
          enableSessionReplay: apiConfig.sessionReplay ?? defaultConfig.enableSessionReplay,
          trackButtonClicks: apiConfig.trackButtonClicks ?? defaultConfig.trackButtonClicks,
          trackCopy: apiConfig.trackCopy ?? defaultConfig.trackCopy,
          trackFormInteractions: apiConfig.trackFormInteractions ?? defaultConfig.trackFormInteractions,
          featureFlagsEnabled: apiConfig.featureFlagsEnabled === true,
        };
      } else {
        console.warn("Failed to fetch tracking config from API, using defaults");
      }
    } catch (error) {
      console.warn("Error fetching tracking config:", error);
    }
  }

  if (resolvedConfig.featureFlagsEnabled) {
    const result = await fetchFeatureFlags(analyticsHost, siteId, namespace, visitorId);
    resolvedConfig.featureFlagsEnabled = result.enabled;
    resolvedConfig.featureFlags = result.flags;
  }
  return resolvedConfig;
}
